spring:
  datasource:
    url: jdbc:mysql://xxxxxxxxx:3306/free-fs?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: xxxxxxxxx
    password: xxxxxxxxx
    driver-class-name: com.mysql.cj.jdbc.Driver

fs:
  isPreview: false
